export const bookmarks = [
  { name: 'Node.js CN', url: 'https://nodejs.cn' },
  { name: 'TSConfig Reference', url: 'https://www.typescriptlang.org/tsconfig' },
  {
    name: 'JSDoc Reference',
    url: 'https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html',
  },
  {
    name: 'MDN',
    url: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects',
  },
  { name: 'Axios', url: 'https://axios-http.com/zh' },
  { name: 'Pnpm', url: 'https://pnpm.io/zh' },
  { name: 'Prettier', url: 'https://prettier.io' },
  { name: 'Eslint', url: 'https://eslint.org/docs/latest/rules' },
  { name: 'Vite', url: 'https://cn.vitejs.dev/config' },
  { name: 'Vitest', url: 'https://cn.vitest.dev' },
  { name: 'Vue 3', url: 'https://cn.vuejs.org' },
  { name: 'Vue Router 4', url: 'https://router.vuejs.org/zh' },
  { name: 'Pinia', url: 'https://pinia.vuejs.org/zh' },
  { name: 'Vuex', url: 'https://vuex.vuejs.org/zh' },
  { name: 'Element Plus', url: 'https://element-plus.org/zh-CN' },
  { name: 'Vue 2', url: 'https://v2.cn.vuejs.org' },
  { name: 'Vue Router 3', url: 'https://v3.router.vuejs.org/zh' },
  { name: 'Vuex 3', url: 'https://v3.vuex.vuejs.org/zh' },
  { name: 'Element UI', url: 'https://element.eleme.cn' },
  { name: 'NestJS Docs', url: 'https://docs.nestjs.com' },
  { name: 'NestJS Docs CN', url: 'https://docs.nestjs.cn' },
  { name: 'Prisma Docs', url: 'https://www.prisma.io/docs' },
];
